import Head from "next/head";
import Calendar from "@/components/Calendar/Calendar";
import Header from "@/components/Header/Header";
import ReduxProvider from "@/redux/ReduxProvider/ReduxProvider";
import { firaSans } from "@/components/utils";

const Home = () => {
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReduxProvider>
        <Header />
        <main className={firaSans.className}>
          <Calendar />
        </main>
      </ReduxProvider>
    </>
  );
};
export default Home;
