import Head from "next/head";
import { Inter } from "next/font/google";
import Calendar from "@/components/Calendar/Calendar";
import Header from "@/components/Header/Header";

import ReduxProvider from "@/redux/ReduxProvider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReduxProvider>
        <Header />
        <main className={` ${inter.className}`}>
          <Calendar />
        </main>
      </ReduxProvider>
    </>
  );
};
export default Home;
